--
-- Estrutura da tabela `professor`
--

INSERT INTO `professor` (`nome`) VALUES
('Alcione Miguel Franz'),
('Aldair Silva'),
('Alexandre Heinz'),
('Ana Paula'),
('Andrei Rodrigues'),
('Atanael Louren'),
('Augusto Rodrigues de Lisboa'),
('Breno Talles'),
('Camila Felipe Tonn'),
('Carlos Penna'),
('Cheila Soares'),
('Cláudia Finardi'),
('Cleiton Edacir'),
('Coffe Break'),
('Danilo Vieira'),
('Darcy Ribeiro'),
('Douglas Moreira'),
('Douglas Siegel'),
('Edmar Delilo'),
('Edson Carvalho'),
('Edson Cruz'),
('Eugenio Pazini'),
('Everton Lisboa'),
('Fabiana Dallmann'),
('Fabio Hermann'),
('Fabio Lima'),
('Fábio Rosa  '),
('Fabrício Lohn'),
('Fernanda Flor'),
('Geyson'),
('Gilson Luis Rufino'),
('Gilson Rufino'),
('Giselle Barcelos'),
('Helton Espezim'),
('Ibanez Guterres'),
('Jackson Pinheiro'),
('Janaína Cardoso'),
('Jeferson Koslovoski'),
('Jimena Kirchner'),
('João Bucciano  '),
('João Silveira'),
('Jorge Souza'),
('José Junior'),
('José Silva'),
('Karla Cristina'),
('Leandro Luis'),
('Lessandra Michel'),
('Luidy Mateus'),
('Magda Ramos'),
('Maicon Pereira'),
('Mariana Chaves'),
('Mario Nascimento'),
('Marlon D Avila'),
('Mateus Gonçalves'),
('Max Andrade'),
('Mery Cristina'),
('Mônica Kremer'),
('Não Haverá'),
('Nivaldo Assis '),
('Pedro Rachadel'),
('Priscila Clézia'),
('Rafael Duarte'),
('Rafael Lindemann'),
('Rafael Silveira'),
('Renan Luis'),
('Roberto Dusik'),
('Roberto Machado'),
('Rodrigo Dias'),
('Rodrigo Luis'),
('Rodrigo Pacheco'),
('Rodrigo Santos'),
('Roger Pardim'),
('Rogerio Mendonça'),
('Sheila Travessa'),
('Sônia Moreira'),
('Sônia Pinto'),
('Susan Thiesen'),
('Tatiana Lee Marques'),
('Tatiana Marques'),
('Teófilo Junior'),
('Thiago Carrano'),
('Tiago Medeiros'),
('Tiago Moreira'),
('Urânia Rickes'),
('Vanusa Feijo'),
('Vinicius Silva'),
('Vinicius Silveira');

-- --------------------------------------------------------

--
-- Estrutura da tabela `sala`
--

INSERT INTO `sala` (`nome`) VALUES
('101'),
('102'),
('201'),
('202'),
('203'),
('204'),
('205'),
('206'),
('303'),
('304'),
('305'),
('306'),
('307'),
('401'),
('402'),
('403'),
('501'),
('502'),
('503'),
('504'),
('505'),
('506'),
('511'),
('512'),
('513'),
('514'),
('515'),
('516'),
('517'),
('521'),
('522'),
('523'),
('524'),
('525'),
('526'),
('527'),
('603'),
('701'),
('702'),
('703'),
('704'),
('705'),
('706'),
('707'),
('708 '),
('AuditÃ³rio'),
('NÃ£o HaverÃ¡ Aula');

-- --------------------------------------------------------

--
-- Estrutura da tabela `tipo`
--

INSERT INTO `tipo` (`nome`) VALUES
('APRENDIZAGEM'),
('ENSINO MÉDIO'),
('QUALIFICAÇÃO'),
('TÉCNICO');

-- --------------------------------------------------------

--
-- Estrutura da tabela `turma`
--

INSERT INTO `turma` (`nome`, `turno`) VALUES
('Artc. Eletrônica 18/1', 'Vespertino'),
('Artc. Eletrônica 17/1', 'Vespertino'),
('Artc. Informática 17/1', 'Vespertino'),
('Eletrônica 18/1', 'Noturno'),
('Eletrônica 17/1', 'Noturno'),
('Eletrotécnica 18/1', 'Noturno'),
('Eletrotécnica 17/2', 'Noturno'),
('Eletrotécnica 17/1', 'Noturno'),
('Eletrotécnica 16/2', 'Noturno'),
('Desenvolvimento de Sistemas 18/1', 'Noturno'),
('Informática 17/1', 'Noturno'),
('Refrigeração e Climatização 18/1', 'Noturno'),
('Refrigeração e Climatização 17/1', 'Noturno'),
('Telecomunicações 18/1', 'Noturno'),
('EaD - Automação Industrial 17/2', 'Noturno'),
('EaD - Segurança do Trabalho 18/1', 'Noturno'),
('CT INF 17/1 V1', 'Verpertino'),
('CT INF 16/1 V1', 'Verpertino'),
('CT INF 17/1 N1', 'Noturno'),
('CT INF 16/1 N1', 'Noturno'),
('CT TELO 16/1 N1', 'Noturno'),
('CT TELO 17/1 V1', 'Verpertino'),
('CT TELO 17/1 N1', 'Noturno'),
('CT TELT 17/2 N1', 'Noturno'),
('CT TELT 17/1 N1', 'Noturno'),
('CT TELT 16/2 N1', 'Noturno'),
('CT TELT 16/1 N1', 'Noturno'),
('CT TRCL 17/1 N1', 'Noturno'),
('CT TRCL 16/1 N1', 'Noturno'),
('CT AUT IND EaD 17/2 N1', 'Noturno'),
('Eletrônico 17/2 V1', 'Verpertino'),
('Suporte 17/1 V1', 'Verpertino'),
('PRET 17/1 V1', 'Verpertino'),
('AEMI 17/2 V1', 'Verpertino'),
('ASSISTENTE ADM. 17/2 M5', 'Matutino'),
('ASSISTENTE ADM. 17/2 V1', 'Verpertino'),
('ASSISTENTE ADM. 17/1 V2', 'Verpertino'),
('ASSISTENTE ADM. 17/1 V4', 'Verpertino'),
('SMMR 17/1 M1', 'Matutino'),
('Redes Locais 17/1 M1', 'Matutino'),
('Logística 17/1 V2', 'Verpertino'),
('ELETRECISTA PREDIAL 17/2 V1', 'Verpertino'),
('ELETRECISTA PREDIAL 2017/2 N1', 'Noturno'),
('DEPENDÊCIA CT-REDES', 'Noturno'),
('DEPENDÊCIA CT-EDIFICAÇÕES', 'Noturno'),
('DEPENDÊCIA CT-REFRIGERAÇÃO', 'Noturno'),
('MARCENEIRO 17/2 V1', 'Verpertino'),
('ELETRECISTA PREDIAL 17/2 V1', 'Verpertino'),
('ELETRECISTA PREDIAL 17/2 N1', 'Noturno'),
('DESENHISTA MECÂNCO 17/1 N1', 'Noturno'),
('DESENHISTA MECÂNICO QP-DEME 2017/2 N1', 'Noturno'),
('MECÂNICOÇÃO QP-MRCR 2017/1 N1', 'Noturno'),
('MECÂNICOÇÃO QP-MERE 2017/2 N1', 'Noturno'),
('MARCENEIRO QP-MARC 2017/2 N1', 'Noturno'),
('MARCENEIRO QP-MARC 2018/1 N1', 'Noturno'),
('NR10 17/2 M1', 'Matutino'),
('COSTURA 17/2 V1', 'Verpertino'),
('Eletricista de Manutenção 17/2 V1', 'Verpertino'),
('Eletricista de Instalações Industriais 17/1 M1', 'Matutino'),
('Telecomunicações 17/1 V1', 'Verpertino'),
('ENCONTRO INTERATIVO', 'Verpertino'),
('CONSELHO DE CLASSE', 'Verpertino'),
('ASSISTENTE ADM. 18/1 V1', 'Verpertino'),
('TELECOM 18/1 V1', 'Verpertino'),
('LOGÍSTICA 18/1 V1', 'Verpertino'),
('ASSISTENTE ADM. 17/2 M1', 'Matutino'),
('ASSISTENTE ADM. 17/2 M5', 'Matutino'),
('SUPORTE 18/1 M1', 'Matutino'),
('EM - 1º ANO A', 'Matutino'),
('EM - 1º ANO B', 'Matutino'),
('EM - 2º ANO', 'Matutino'),
('EM - 3º ANO A', 'Matutino'),
('EM - 3º ANO B', 'Matutino'),
('QA- DESENHISTA CONSTRUÇÃO CIVIL 2017/2 M1', 'Matutino'),
('AI LOGÍSTICA 2017/1 V2', 'Vespertino'),
('EVENTOS', ''),
('QA-MARCENEIRO 2017/V1', 'Vespertino'),
('VENDA DE LIVROS - EM', ''),
('COSTURA 17/2', 'Vespertino'),
('AI-SMM 2018/V1', 'Vespertino'),
('T-TELO-2017/V1', 'Vespertino'),
('Clube EM', 'Verpertino'),
('Mini Empresa', ''),
('Vida e Carreira', ''),
('Nivelamento Inglês', ''),
('AUTOMAÇÃO EAD', ''),
('AI SMMRL 2018/M1', ''),
('LOGÍSTICA 18/1 M1', ''),
('ASSISTENTE ADM. 18/1 M1', ''),
('Dependência MSI', ''),
('PREDIAL 18/1', ''),
('Reunião NRSC', ''),
('MANUTENÇÃO', ''),
('Dependência Matemática', ''),
('Dependência História', ''),
('Dependência Português', ''),
('Dependência Biologia', ''),
('Clube Comunicação na Prática', ''),
('Clube Retrô Tec Games', ''),
('Clube Teatro', ''),
('Clube de Inglês', ''),
('ASSISTENTE ADM. 18/1 - Precicast', ''),
('Eletricista - CELESC', ''),
('Suporte 18/01', ''),
('Assistente ADM. - Intelbras', ''),
('Mecânico de Refigeração 2018/1 N1', 'Noturno'),
('Eletroeletronica V8 Brasil 2018/1 N1', 'Noturno'),
('Marceneiro 2017/2 N1', 'Noturno');